name: Build and Release
on: [push]

jobs:
    build:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                profiles: 'default'
            - uses: actions/setup-node@v4
              with:
                node-version: '18'
            - name: Build
              uses: actions-rs/cargo@v1
              with:
                command: cargo-bundle
                args: --release